Data Pre-Processing using standard scaler

In [3]:
# Import all neccessary libraries
import pandas as pd
from numpy import set_printoptions
from sklearn.preprocessing import StandardScaler


# Step one : Import the data
dataFileName = "diabete-data.csv"
columnNames = ["Pregnant","Plasma","bPedia","Test","Skin","Bmass","Diastolic","Age","Class"]
readData = pd.read_csv(dataFileName, names = columnNames)
array = readData.values

# Step two : Split the data into input and output
inputData = array[:,0:8]
outputData = array[:,8]

# Step three : Apply the preprocessing transformation
rescaler = StandardScaler().fit(inputData)
rescaledInputData = rescaler.transform(inputData) 

# Step four : Summarize the data and display
set_printoptions(precision=3)
print(rescaledInputData[0:5,:])





[[ 0.64   0.848  0.15   0.907 -0.693  0.204  0.468  1.426]
 [-0.845 -1.123 -0.161  0.531 -0.693 -0.684 -0.365 -0.191]
 [ 1.234  1.944 -0.264 -1.288 -0.693 -1.103  0.604 -0.106]
 [-0.845 -0.998 -0.161  0.155  0.123 -0.494 -0.921 -1.042]
 [-1.142  0.504 -1.505  0.907  0.766  1.41   5.485 -0.02 ]]
