Data Pre-Processing using a Binarizer

In [1]:
# Import all neccessary libraries
import pandas as pd
from numpy import set_printoptions
from sklearn.preprocessing import Binarizer


# Step one : Import the data
dataFileName = "diabete-data.csv"
columnNames = ["Pregnant","Plasma","bPedia","Test","Skin","Bmass","Diastolic","Age","Class"]
readData = pd.read_csv(dataFileName, names = columnNames)
array = readData.values

# Step two : Split the data into input and output
inputData = array[:,0:8]
outputData = array[:,8]

# Step three : Apply the preprocessing transformation
rescaler = Binarizer(threshold = 1.0).fit(inputData)
rescaledInputData = rescaler.transform(inputData) 

# Step four : Summarize the data and display
set_printoptions(precision=3)
print(rescaledInputData[0:5,:])

[[1. 1. 1. 1. 0. 1. 0. 1.]
 [0. 1. 1. 1. 0. 1. 0. 1.]
 [1. 1. 1. 0. 0. 1. 0. 1.]
 [0. 1. 1. 1. 1. 1. 0. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1.]]
