Data Pre-Processing

In [1]:
# Import all neccessary libraries
import pandas as pd
from numpy import set_printoptions
from sklearn.preprocessing import MinMaxScaler


In [2]:
# Step one : Import the data
dataFileName = "diabete-data.csv"
columnNames = ["Pregnant","Plasma","bPedia","Test","Skin","Bmass","Diastolic","Age","Class"]
readData = pd.read_csv(dataFileName, names = columnNames)
array = readData.values

In [3]:
# Step two : Split the data into input and output
inputData = array[:,0:8]
outputData = array[:,8]

In [4]:
# Step three : Apply the preprocessing transformation
rescaler = MinMaxScaler(feature_range = (0,1))
rescaledInputData = rescaler.fit_transform(inputData) 

In [5]:
# Step four : Summarize the data and display
set_printoptions(precision=3)
print(rescaledInputData[0:5,:])

[[0.353 0.744 0.59  0.354 0.    0.501 0.234 0.483]
 [0.059 0.427 0.541 0.293 0.    0.396 0.117 0.167]
 [0.471 0.92  0.525 0.    0.    0.347 0.254 0.183]
 [0.059 0.447 0.541 0.232 0.111 0.419 0.038 0.   ]
 [0.    0.688 0.328 0.354 0.199 0.642 0.944 0.2  ]]
