Data Pre-Processing using a normalizer

In [1]:
# Import all neccessary libraries
import pandas as pd
from numpy import set_printoptions
from sklearn.preprocessing import Normalizer


# Step one : Import the data
dataFileName = "diabete-data.csv"
columnNames = ["Pregnant","Plasma","bPedia","Test","Skin","Bmass","Diastolic","Age","Class"]
readData = pd.read_csv(dataFileName, names = columnNames)
array = readData.values

# Step two : Split the data into input and output
inputData = array[:,0:8]
outputData = array[:,8]

# Step three : Apply the preprocessing transformation
rescaler = Normalizer().fit(inputData)
rescaledInputData = rescaler.transform(inputData) 

# Step four : Summarize the data and display
set_printoptions(precision=3)
print(rescaledInputData[0:5,:])







[[0.034 0.828 0.403 0.196 0.    0.188 0.004 0.28 ]
 [0.008 0.716 0.556 0.244 0.    0.224 0.003 0.261]
 [0.04  0.924 0.323 0.    0.    0.118 0.003 0.162]
 [0.007 0.588 0.436 0.152 0.622 0.186 0.001 0.139]
 [0.    0.596 0.174 0.152 0.731 0.188 0.01  0.144]]
