In [4]:
import numpy as np


In [5]:
array1 = np.array([1,4,5,6])
array1

array([1, 4, 5, 6])

In [7]:
myarray = np.array(array1)
myarray

array([1, 4, 5, 6])

In [8]:
type(myarray)

numpy.ndarray

In [14]:
array2 = np.array([[1,4.9,5.1,5.2],[4.5,6.7,7.1,9.8]])
array3 = np.array([[1,2,3],[4,5,6],[7,8,9]])


In [15]:
array2

array([[1. , 4.9, 5.1, 5.2],
       [4.5, 6.7, 7.1, 9.8]])

In [17]:
array3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
myarray.shape

(4,)

In [22]:
array3.shape


(3, 3)

In [24]:
array3.dtype

dtype('int64')

In [26]:
myarray.size

4

In [28]:
import pandas as pd

In [29]:
df = pd.DataFrame(array3)
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9